camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: true
    admin-user:
      id: admin
      password: admin
    filter:
      create: All Tasks
    history-level: full

spring.h2.console.enabled: true
